import Head from "next/head";
import ChatRoute from "../../main-site/routes/chat.route";
import styles from "../../styles/Home.module.scss";

export default function Chats() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatRoute />
    </div>
  );
}
